# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学业\研究生\研一\数据库系统与原理\admin_opt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_opt(object):
    def setupUi(self, admin_opt):
        admin_opt.setObjectName("admin_opt")
        admin_opt.resize(400, 186)
        self.layoutWidget = QtWidgets.QWidget(admin_opt)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 40, 261, 45))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.admin_opt_combox = QtWidgets.QComboBox(self.layoutWidget)
        self.admin_opt_combox.setObjectName("admin_opt_combox")
        self.admin_opt_combox.addItem("")
        self.admin_opt_combox.addItem("")
        self.admin_opt_combox.addItem("")
        self.admin_opt_combox.addItem("")
        self.admin_opt_combox.addItem("")
        self.admin_opt_combox.addItem("")
        self.verticalLayout.addWidget(self.admin_opt_combox)
        self.layoutWidget1 = QtWidgets.QWidget(admin_opt)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 130, 261, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.admin_push_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.admin_push_button.setObjectName("admin_push_button")
        self.horizontalLayout_2.addWidget(self.admin_push_button)
        self.admin_cancel_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.admin_cancel_button.setObjectName("admin_cancel_button")
        self.horizontalLayout_2.addWidget(self.admin_cancel_button)

        self.retranslateUi(admin_opt)
        QtCore.QMetaObject.connectSlotsByName(admin_opt)

    def retranslateUi(self, admin_opt):
        _translate = QtCore.QCoreApplication.translate
        admin_opt.setWindowTitle(_translate("admin_opt", "Form"))
        self.label.setText(_translate("admin_opt", "选择你要进行的操作"))
        self.admin_opt_combox.setItemText(0, _translate("admin_opt", "统计学院打卡未完成人数"))
        self.admin_opt_combox.setItemText(1, _translate("admin_opt", "修改学生信息"))
        self.admin_opt_combox.setItemText(2, _translate("admin_opt", "查询学生打卡/核酸情况"))
        self.admin_opt_combox.setItemText(3, _translate("admin_opt", "统计当日未打卡/核酸的学生信息"))
        self.admin_opt_combox.setItemText(4, _translate("admin_opt", "统计连续多日未打卡/核酸的学生信息"))
        self.admin_opt_combox.setItemText(5, _translate("admin_opt", "增加学生信息"))
        self.admin_push_button.setText(_translate("admin_opt", "确定"))
        self.admin_cancel_button.setText(_translate("admin_opt", "取消"))
