# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学业\研究生\研一\数据库系统与原理\健康打卡系统\clockin_system\add_stu_clockin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_stu_clockin(object):
    def setupUi(self, add_stu_clockin):
        add_stu_clockin.setObjectName("add_stu_clockin")
        add_stu_clockin.resize(379, 203)
        self.layoutWidget = QtWidgets.QWidget(add_stu_clockin)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 307, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.student_id_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.student_id_input.setObjectName("student_id_input")
        self.horizontalLayout.addWidget(self.student_id_input)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.layoutWidget1 = QtWidgets.QWidget(add_stu_clockin)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 150, 195, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.commit_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.commit_button.setObjectName("commit_button")
        self.horizontalLayout_4.addWidget(self.commit_button)
        self.return_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_4.addWidget(self.return_button)
        self.widget = QtWidgets.QWidget(add_stu_clockin)
        self.widget.setGeometry(QtCore.QRect(11, 70, 361, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.clockin_time = QtWidgets.QDateTimeEdit(self.widget)
        self.clockin_time.setObjectName("clockin_time")
        self.horizontalLayout_2.addWidget(self.clockin_time)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.location_combox = QtWidgets.QComboBox(self.widget)
        self.location_combox.setObjectName("location_combox")
        self.location_combox.addItem("")
        self.location_combox.addItem("")
        self.horizontalLayout_2.addWidget(self.location_combox)
        self.widget1 = QtWidgets.QWidget(add_stu_clockin)
        self.widget1.setGeometry(QtCore.QRect(10, 110, 291, 23))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)

        self.retranslateUi(add_stu_clockin)
        QtCore.QMetaObject.connectSlotsByName(add_stu_clockin)

    def retranslateUi(self, add_stu_clockin):
        _translate = QtCore.QCoreApplication.translate
        add_stu_clockin.setWindowTitle(_translate("add_stu_clockin", "添加学生打卡信息"))
        self.label_2.setText(_translate("add_stu_clockin", "添加学号为"))
        self.label.setText(_translate("add_stu_clockin", "的同学"))
        self.commit_button.setText(_translate("add_stu_clockin", "确认"))
        self.return_button.setText(_translate("add_stu_clockin", "返回"))
        self.label_3.setText(_translate("add_stu_clockin", "在时间为"))
        self.label_5.setText(_translate("add_stu_clockin", "地点为"))
        self.location_combox.setItemText(0, _translate("add_stu_clockin", "创新港"))
        self.location_combox.setItemText(1, _translate("add_stu_clockin", "兴庆"))
        self.comboBox.setItemText(0, _translate("add_stu_clockin", "是"))
        self.comboBox.setItemText(1, _translate("add_stu_clockin", "否"))
        self.label_4.setText(_translate("add_stu_clockin", "完成核酸检测的健康打卡信息"))
