# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学业\研究生\研一\数据库系统与原理\check_stu_tel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_stu_tel(object):
    def setupUi(self, check_stu_tel):
        check_stu_tel.setObjectName("check_stu_tel")
        check_stu_tel.resize(493, 281)
        self.widget = QtWidgets.QWidget(check_stu_tel)
        self.widget.setGeometry(QtCore.QRect(13, 10, 464, 261))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.apartment_combox = QtWidgets.QComboBox(self.widget)
        self.apartment_combox.setObjectName("apartment_combox")
        self.apartment_combox.addItem("")
        self.apartment_combox.addItem("")
        self.apartment_combox.addItem("")
        self.horizontalLayout.addWidget(self.apartment_combox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.project_combox = QtWidgets.QComboBox(self.widget)
        self.project_combox.setObjectName("project_combox")
        self.project_combox.addItem("")
        self.project_combox.addItem("")
        self.horizontalLayout.addWidget(self.project_combox)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.show_table = QtWidgets.QTableWidget(self.widget)
        self.show_table.setObjectName("show_table")
        self.show_table.setColumnCount(0)
        self.show_table.setRowCount(0)
        self.verticalLayout.addWidget(self.show_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_button = QtWidgets.QPushButton(self.widget)
        self.check_button.setObjectName("check_button")
        self.horizontalLayout_2.addWidget(self.check_button)
        self.return_button = QtWidgets.QPushButton(self.widget)
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_2.addWidget(self.return_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(check_stu_tel)
        QtCore.QMetaObject.connectSlotsByName(check_stu_tel)

    def retranslateUi(self, check_stu_tel):
        _translate = QtCore.QCoreApplication.translate
        check_stu_tel.setWindowTitle(_translate("check_stu_tel", "Form"))
        self.label.setText(_translate("check_stu_tel", "居住在"))
        self.apartment_combox.setItemText(0, _translate("check_stu_tel", "创新港"))
        self.apartment_combox.setItemText(1, _translate("check_stu_tel", "兴庆"))
        self.apartment_combox.setItemText(2, _translate("check_stu_tel", "全部"))
        self.label_2.setText(_translate("check_stu_tel", "校区未完成今日"))
        self.project_combox.setItemText(0, _translate("check_stu_tel", "健康打卡"))
        self.project_combox.setItemText(1, _translate("check_stu_tel", "核酸采样"))
        self.label_3.setText(_translate("check_stu_tel", "的同学联系方式"))
        self.check_button.setText(_translate("check_stu_tel", "查找"))
        self.return_button.setText(_translate("check_stu_tel", "返回"))
