# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学业\研究生\研一\数据库系统与原理\check_department.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_department(object):
    def setupUi(self, check_department):
        check_department.setObjectName("check_department")
        check_department.resize(438, 157)
        self.widget = QtWidgets.QWidget(check_department)
        self.widget.setGeometry(QtCore.QRect(40, 30, 341, 94))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.department_combox = QtWidgets.QComboBox(self.widget)
        self.department_combox.setObjectName("department_combox")
        self.horizontalLayout.addWidget(self.department_combox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.project_combox = QtWidgets.QComboBox(self.widget)
        self.project_combox.setObjectName("project_combox")
        self.project_combox.addItem("")
        self.project_combox.addItem("")
        self.horizontalLayout.addWidget(self.project_combox)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_lcd = QtWidgets.QLCDNumber(self.widget)
        self.result_lcd.setObjectName("result_lcd")
        self.verticalLayout.addWidget(self.result_lcd)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_button = QtWidgets.QPushButton(self.widget)
        self.check_button.setObjectName("check_button")
        self.horizontalLayout_2.addWidget(self.check_button)
        self.return_button = QtWidgets.QPushButton(self.widget)
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_2.addWidget(self.return_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(check_department)
        QtCore.QMetaObject.connectSlotsByName(check_department)

    def retranslateUi(self, check_department):
        _translate = QtCore.QCoreApplication.translate
        check_department.setWindowTitle(_translate("check_department", "Form"))
        self.label.setText(_translate("check_department", "统计"))
        self.label_2.setText(_translate("check_department", "当天未完成"))
        self.project_combox.setItemText(0, _translate("check_department", "核酸检测"))
        self.project_combox.setItemText(1, _translate("check_department", "健康打卡"))
        self.label_3.setText(_translate("check_department", "人数"))
        self.check_button.setText(_translate("check_department", "查询"))
        self.return_button.setText(_translate("check_department", "返回"))
