# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学业\研究生\研一\数据库系统与原理\history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_history(object):
    def setupUi(self, history):
        history.setObjectName("history")
        history.resize(616, 300)
        self.tableWidget = QtWidgets.QTableWidget(history)
        self.tableWidget.setGeometry(QtCore.QRect(40, 80, 531, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(history)
        self.widget.setGeometry(QtCore.QRect(40, 20, 531, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.student_id_input = QtWidgets.QLineEdit(self.widget)
        self.student_id_input.setObjectName("student_id_input")
        self.horizontalLayout.addWidget(self.student_id_input)
        self.check_button = QtWidgets.QPushButton(self.widget)
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        self.return_button = QtWidgets.QPushButton(self.widget)
        self.return_button.setObjectName("return_button")
        self.horizontalLayout.addWidget(self.return_button)

        self.retranslateUi(history)
        QtCore.QMetaObject.connectSlotsByName(history)

    def retranslateUi(self, history):
        _translate = QtCore.QCoreApplication.translate
        history.setWindowTitle(_translate("history", "Form"))
        self.label.setText(_translate("history", "学号"))
        self.check_button.setText(_translate("history", "查看"))
        self.return_button.setText(_translate("history", "返回"))
