# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\学业\研究生\研一\数据库系统与原理\student.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_student_push(object):
    def setupUi(self, student_push):
        student_push.setObjectName("student_push")
        student_push.resize(244, 344)
        self.layoutWidget = QtWidgets.QWidget(student_push)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 280, 221, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button = QtWidgets.QPushButton(self.layoutWidget)
        self.push_button.setObjectName("push_button")
        self.horizontalLayout.addWidget(self.push_button)
        self.cancel_button = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.layoutWidget1 = QtWidgets.QWidget(student_push)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 221, 245))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.student_id_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.student_id_input.setObjectName("student_id_input")
        self.verticalLayout.addWidget(self.student_id_input)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.department_combox = QtWidgets.QComboBox(self.layoutWidget1)
        self.department_combox.setObjectName("department_combox")
        self.verticalLayout.addWidget(self.department_combox)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pcr_done_combox = QtWidgets.QComboBox(self.layoutWidget1)
        self.pcr_done_combox.setObjectName("pcr_done_combox")
        self.pcr_done_combox.addItem("")
        self.pcr_done_combox.addItem("")
        self.verticalLayout.addWidget(self.pcr_done_combox)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.apartment_combox = QtWidgets.QComboBox(self.layoutWidget1)
        self.apartment_combox.setObjectName("apartment_combox")
        self.apartment_combox.addItem("")
        self.apartment_combox.addItem("")
        self.verticalLayout.addWidget(self.apartment_combox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.check_history_button = QtWidgets.QPushButton(student_push)
        self.check_history_button.setGeometry(QtCore.QRect(10, 310, 221, 21))
        self.check_history_button.setObjectName("check_history_button")

        self.retranslateUi(student_push)
        QtCore.QMetaObject.connectSlotsByName(student_push)

    def retranslateUi(self, student_push):
        _translate = QtCore.QCoreApplication.translate
        student_push.setWindowTitle(_translate("student_push", "Form"))
        self.push_button.setText(_translate("student_push", "提交"))
        self.cancel_button.setText(_translate("student_push", "取消"))
        self.label.setText(_translate("student_push", "学号"))
        self.label_2.setText(_translate("student_push", "学院"))
        self.label_3.setText(_translate("student_push", "是否完成核酸采样"))
        self.pcr_done_combox.setItemText(0, _translate("student_push", "是"))
        self.pcr_done_combox.setItemText(1, _translate("student_push", "否"))
        self.label_4.setText(_translate("student_push", "当前居住地"))
        self.apartment_combox.setItemText(0, _translate("student_push", "创新港"))
        self.apartment_combox.setItemText(1, _translate("student_push", "兴庆"))
        self.check_history_button.setText(_translate("student_push", "查看历史打卡记录"))
